name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
            pip install --upgrade pip
            pip install scikit-build pytest numpy scipy pytest-xdist
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements.txt
        name: Install requirements.txt
      - run: |
            python3 setup.py install
            rm -rf symfem
        name: Install symfem
      - run: |
            git clone https://github.com/FEniCS/basix.git basix-src
            cd basix-src
            pip install .
        name: Install basix
      - run: python3 -m pytest -n=auto --durations=50 test/ --has-basix 1
        name: Run unit tests
